apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-2005"
  description: "demo"
  annotations:
    github.com/project-slug: leemills83/demo-2005
    backstage.io/techdocs-ref: url:https://github.com//leemills83/demo-2005
spec:
  type: website
  lifecycle: experimental
  owner: "leemills83"
